python /media/gsadmin/vd3/xudongliang/software/stringtie-2.0.6.Linux_x86_64/db/prepDE.py -i /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/gtf.list -g /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/gene_count_matrix.csv -t /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/transcript_count_matrix.csv
sed -i 's/,/\t/g' /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/gene_count_matrix.csv
sed -i 's/\r//g' /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/gene_count_matrix.csv
sed -i 's/,/\t/g' /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/transcript_count_matrix.csv
sed -i 's/\r//g' /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/transcript_count_matrix.csv
perl /media/gsadmin/vd3/xudongliang/pipeline/RNA_seq/util/trans_count_fmt.pl -g /media/gsadmin/vd3/xudongliang/database/gencode/release_32/gencode.v32.annotation.mRNA.fmt.gtf -c /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/transcript_count_matrix.csv > /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/transcript_count_matrix.fmt.csv
/media/gsadmin/vd1/heguangliang/bcbio3/anaconda/bin/Rscript /media/gsadmin/vd3/xudongliang/pipeline/RNA_seq/util/ballgown_fpkm.R /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/45,/media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/46,/media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/47,/media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/48,/media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/49,/media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/50 /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result &> /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/log/ballgown.log
sed -i "s/FPKM.//g" /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/genes.fpkm.xls
sed -i "s/FPKM.//g" /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/trans.fpkm.xls
/media/gsadmin/vd1/heguangliang/bcbio3/anaconda/bin/Rscript /media/gsadmin/vd3/xudongliang/pipeline/RNA_seq/util/fpkm_density.R /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/genes.fpkm.xls /media/gsadmin/vd3/xudongliang/project/20190906/report/03_mRNA_Analysis/01_mRNA_Expression_Profile/mRNA_Expression_Figures/fpkm.density.pdf &> /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/log/fpkm_density.log
/media/gsadmin/vd1/heguangliang/bcbio3/anaconda/bin/Rscript /media/gsadmin/vd3/xudongliang/pipeline/RNA_seq/util/Deseq2_PCA.R /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/gene_count_matrix.csv /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/ &> /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/log/deseq2.log
perl /media/gsadmin/vd3/xudongliang/pipeline/RNA_seq/util/trans.tpm.stat.pl /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/gtf.list /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/trans.tpm.xls
/media/gsadmin/vd1/heguangliang/bcbio3/anaconda/bin/Rscript /media/gsadmin/vd3/xudongliang/pipeline/RNA_seq/util/cor.r /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/count.norm.xls /media/gsadmin/vd3/xudongliang/project/20190906/report/03_mRNA_Analysis/01_mRNA_Expression_Profile/mRNA_Expression_Figures &> /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/log/cor.log
/media/gsadmin/vd1/heguangliang/bcbio3/anaconda/bin/Rscript  /media/gsadmin/vd3/xudongliang/pipeline/RNA_seq/util/pca_plot.R /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/count.rlog.xls /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/sample.groups /media/gsadmin/vd3/xudongliang/project/20190906/report/03_mRNA_Analysis/01_mRNA_Expression_Profile/mRNA_Expression_Figures &> /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/log/pca.log
/media/gsadmin/vd1/heguangliang/bcbio3/anaconda/bin/Rscript /media/gsadmin/vd3/xudongliang/pipeline/RNA_seq/util/tsne_plot.R /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/count.rlog.xls /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/result/sample.groups /media/gsadmin/vd3/xudongliang/project/20190906/report/03_mRNA_Analysis/01_mRNA_Expression_Profile/mRNA_Expression_Figures &> /media/gsadmin/vd3/xudongliang/project/20190906/data_analysis/mRNA/gene_profile/log/tsne.log
