/media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/bwa mem -t 16 -M -Y -R "@RG\tID:normal\tPL:ILLUMINA\tLB:normal\tSM:normal" /media/gsadmin/vd1/heguangliang/pipeline/WGS/database/reference/hg19/hg19.fa /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/normal/clean_data/normal_R1.fastq.gz /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/normal/clean_data/normal_R2.fastq.gz | /media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/sambamba view -S  -t 16 -f bam /dev/stdin | /media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/sambamba sort -m 8G -t 16 -o /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/normal/tmp_alignment/normal.sorted.bam /dev/stdin
ln -sf /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/normal/tmp_alignment/normal.sorted.bam /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/normal/tmp_alignment/normal.sorted.markdup.bam && ln -sf /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/normal/tmp_alignment/normal.sorted.bam.bai /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/normal/tmp_alignment/normal.sorted.markdup.bam.bai
/media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/gatk BaseRecalibrator --java-options "-XX:+UseParallelGC -XX:ParallelGCThreads=20" -R /media/gsadmin/vd1/heguangliang/pipeline/WGS/database/reference/hg19/hg19.fa  -I /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/normal/tmp_alignment/normal.sorted.markdup.bam --known-sites /media/gsadmin/vd1/heguangliang/pipeline/WGS/database/gatk_bundle/hg19/1000G_phase1_tumor550_custom.snps.high_confidence.hg19.vcf.gz --known-sites /media/gsadmin/vd1/heguangliang/pipeline/WGS/database/gatk_bundle/hg19/Mills_and_1000G_gold_standard.indels.hg19.vcf.gz --known-sites /media/gsadmin/vd1/heguangliang/pipeline/WGS/database/gatk_bundle/hg19/dbsnp_150_tumor550_custom.hg19.vcf.gz -O /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/normal/tmp_alignment/normal.sorted.markdup.recal_data.table
/media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/gatk ApplyBQSR --bqsr-recal-file /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/normal/tmp_alignment/normal.sorted.markdup.recal_data.table -R /media/gsadmin/vd1/heguangliang/pipeline/WGS/database/reference/hg19/hg19.fa -I /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/normal/tmp_alignment/normal.sorted.markdup.bam -O /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/normal/tmp_alignment/normal.sorted.markdup.BQSR.bam
mv /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/normal/tmp_alignment/normal.sorted.markdup.BQSR.bam /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/normal/result_alignment/normal.sorted.markdup.BQSR.bam && /media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/sambamba index /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/normal/result_alignment/normal.sorted.markdup.BQSR.bam
source activate python3 && python3 /media/gsadmin/vd1/heguangliang/project/report_system/cancer/chemotherapy.py -b /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/normal/result_alignment/normal.sorted.markdup.BQSR.bam -c 宫颈癌 -o /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/report/化疗报告.docx && source deactivate
echo align normal finished >>/media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/finishedSampleAnalysis.log
/media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/bwa mem -t 16 -M -Y -R "@RG\tID:tumor\tPL:ILLUMINA\tLB:tumor\tSM:tumor" /media/gsadmin/vd1/heguangliang/pipeline/WGS/database/reference/hg19/hg19.fa /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/tumor/clean_data/tumor_R1.fastq.gz /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/tumor/clean_data/tumor_R2.fastq.gz | /media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/sambamba view -S  -t 16 -f bam /dev/stdin | /media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/sambamba sort -m 8G -t 16 -o /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/tumor/tmp_alignment/tumor.sorted.bam /dev/stdin
ln -sf /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/tumor/tmp_alignment/tumor.sorted.bam /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/tumor/tmp_alignment/tumor.sorted.markdup.bam && ln -sf /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/tumor/tmp_alignment/tumor.sorted.bam.bai /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/tumor/tmp_alignment/tumor.sorted.markdup.bam.bai
/media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/gatk BaseRecalibrator --java-options "-XX:+UseParallelGC -XX:ParallelGCThreads=20" -R /media/gsadmin/vd1/heguangliang/pipeline/WGS/database/reference/hg19/hg19.fa  -I /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/tumor/tmp_alignment/tumor.sorted.markdup.bam --known-sites /media/gsadmin/vd1/heguangliang/pipeline/WGS/database/gatk_bundle/hg19/1000G_phase1_tumor550_custom.snps.high_confidence.hg19.vcf.gz --known-sites /media/gsadmin/vd1/heguangliang/pipeline/WGS/database/gatk_bundle/hg19/Mills_and_1000G_gold_standard.indels.hg19.vcf.gz --known-sites /media/gsadmin/vd1/heguangliang/pipeline/WGS/database/gatk_bundle/hg19/dbsnp_150_tumor550_custom.hg19.vcf.gz -O /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/tumor/tmp_alignment/tumor.sorted.markdup.recal_data.table
/media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/gatk ApplyBQSR --bqsr-recal-file /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/tumor/tmp_alignment/tumor.sorted.markdup.recal_data.table -R /media/gsadmin/vd1/heguangliang/pipeline/WGS/database/reference/hg19/hg19.fa -I /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/tumor/tmp_alignment/tumor.sorted.markdup.bam -O /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/tumor/tmp_alignment/tumor.sorted.markdup.BQSR.bam
mv /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/1.process/tumor/tmp_alignment/tumor.sorted.markdup.BQSR.bam /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/tumor/result_alignment/tumor.sorted.markdup.BQSR.bam
/media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/sambamba index /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/tumor/result_alignment/tumor.sorted.markdup.BQSR.bam
echo align tumor finished >>/media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/finishedSampleAnalysis.log
