perl /media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/convert2annovar.pl -format vcf4 /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/normal/result_variation/snp_indel/normal.final.snp_indel.vcf.gz --outfile /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/normal/result_variation/snp_indel/normal.snp_indel.avinput --includeinfo 
perl /media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/table_annovar.pl /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/normal/result_variation/snp_indel/normal.snp_indel.avinput /media/gsadmin/vd1/heguangliang/pipeline/WGS/database/annovar/hg19 -buildver hg19 -out /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/normal/result_variation/snp_indel/normal.snp_indel --remove -nastring -- --polish --thread 8 --csvout  --otherinfo -protocol refGene,cytoBand,1000g_ALL.sites.2015_08,avsnp150,clinvar_20180729,cosmic85_coding,cosmic85_noncoding,dbnsfp33a,exac03,gnomad_exome,gnomad_genome,intervar,hgmd,esp6500siv2_all,omim201806 -operation g,r,f,f,f,f,f,f,f,f,f,f,f,f,f 
/media/gsadmin/vd1/heguangliang/bcbio3/anaconda/envs/DNA_pipeline_python2/bin/python /media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/proannovar.py -i /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/normal/result_variation/snp_indel/normal.snp_indel.hg19_multianno.csv -o /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/normal/result_variation/snp_indel/normal.snp_indel.hg19_multianno.pro.csv
echo annotate normal finished >>/media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/finishedSampleAnalysis.log 
#perl /media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/convert2annovar.pl -format vcf4 /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/tumor/result_variation/snp_indel/tumor.3tools.vcf.gz --outfile /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/tumor/result_variation/snp_indel/tumor.snp_indel.avinput --includeinfo 
#perl /media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/table_annovar.pl /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/tumor/result_variation/snp_indel/tumor.snp_indel.avinput /media/gsadmin/vd1/heguangliang/pipeline/WGS/database/annovar/hg19 -buildver hg19 -out /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/tumor/result_variation/snp_indel/tumor.snp_indel --remove -nastring -- --polish --thread 8 --csvout  --otherinfo -protocol refGene,cytoBand,1000g_ALL.sites.2015_08,avsnp150,clinvar_20180729,cosmic85_coding,cosmic85_noncoding,dbnsfp33a,exac03,gnomad_exome,gnomad_genome,intervar,hgmd,esp6500siv2_all -operation g,r,f,f,f,f,f,f,f,f,f,f,f,f 
#perl /media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/convert2annovar.pl -format vcf4 /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/tumor/result_variation/cnv_sv/tumor.final.cnv_sv.vcf.gz --outfile /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/tumor/result_variation/cnv_sv/tumor.cnv_sv.avinput --includeinfo 
#perl /media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/table_annovar.pl /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/tumor/result_variation/cnv_sv/tumor.cnv_sv.avinput /media/gsadmin/vd1/heguangliang/pipeline/WGS/database/annovar/hg19 -buildver hg19 -out /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/tumor/result_variation/cnv_sv/tumor.cnv_sv --remove -nastring -- --polish --thread 8 --csvout  --otherinfo -protocol refGene,cytoBand,1000g_ALL.sites.2015_08,avsnp150,clinvar_20180729,cosmic85_coding,cosmic85_noncoding,dbnsfp33a,exac03,gnomad_exome,gnomad_genome,intervar,hgmd,esp6500siv2_all -operation g,r,f,f,f,f,f,f,f,f,f,f,f,f 
#perl /media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/convert2annovar.pl -format vcf4 /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/tumor/result_variation/cnv_sv/tumor_battenberg_cn.vcf.gz --outfile /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/tumor/result_variation/cnv_sv/tumor_battenberg_cn.avinput --includeinfo 
#perl /media/gsadmin/vd1/heguangliang/pipeline/WGS/bin/table_annovar.pl /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/tumor/result_variation/cnv_sv/tumor_battenberg_cn.avinput /media/gsadmin/vd1/heguangliang/pipeline/WGS/database/annovar/hg19 -buildver hg19 -out /media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/2.result/tumor/result_variation/cnv_sv/tumor_battenberg_cn --remove -nastring -- --polish --thread 8 --csvout  --otherinfo -protocol refGene,cytoBand,1000g_ALL.sites.2015_08,avsnp150,clinvar_20180729,cosmic85_coding,cosmic85_noncoding,dbnsfp33a,exac03,gnomad_exome,gnomad_genome,intervar,hgmd,esp6500siv2_all -operation g,r,f,f,f,f,f,f,f,f,f,f,f,f 
#echo annotate tumor finished >>/media/gsadmin/vd2/data/zl/20181229LYF/Target_hg19_work_dir/finishedSampleAnalysis.log 
